name: live_streaming_with_cohosting
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  zego_express_engine: ^3.2.1
  permission_handler: ^10.2.0
  encrypt: ^5.0.1
  zego_zim: ^2.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
  - assets/icons/
