name: call_with_invitation
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  zego_express_engine: ^3.2.1
  zego_zim: 2.6.0+1
  permission_handler: ^10.2.0
  encrypt: ^5.0.1
  wakelock: ^0.6.2
  flutter_styled_toast: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/

  
  
  
  
  
  
  
  
  
  
  
